name: pitu_app
description: "PetBienestar — gestión del cuidado y la salud de mascotas (local-first)."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  uuid: ^4.5.1
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
